# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano
    shield: helix_left
  - board: nice_nano
    shield: helix_right
  - board: preonic
  - board: planck
  - board: nice_nano
    shield: settings_reset
