# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano@1//zmk
    shield: helix_left
  - board: nice_nano@1//zmk
    shield: helix_right
  - board: nice_nano//zmk
    shield: helix_4row_left
  - board: nice_nano//zmk
    shield: helix_4row_right
  - board: planck//zmk
  - board: lpgalaxy_blank_slate
  - board: nice_nano@1//zmk
    shield: settings_reset
